# Generated by Django 4.0.4 on 2022-05-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='ids',
        ),
        migrations.AddField(
            model_name='measurement',
            name='ids',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Measurement', to='measurement.sensor'),
            preserve_default=False,
        ),
    ]
