# Generated by Django 4.0.4 on 2022-05-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_measurement_ids_measurement_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Measurement', to='measurement.sensor', verbose_name='ID датчика'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
