# Generated by Django 4.0.4 on 2022-05-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_ids_alter_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(blank=True, max_length=40, verbose_name='Описание'),
        ),
    ]
