# Generated by Django 4.0.4 on 2022-05-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_measurement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='ids',
            new_name='sensor',
        ),
    ]
