# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32-4",
  "description": "Датчик на кухне за холодильником 2"
}

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "WIFI",
  "description":"кухня"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/7/
Content-Type: application/json

{
  "description": "2 датчик в команту 5"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 10,
  "temperature": 21.3
}


###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type:  multipart/form-data

{
  "sensor": 8,
  "temperature": 28.3,
  "image": "D:/Django/dj-homeworks/3.1-drf-intro/smart_home/media/user01.png"
}
###

# получение информации по датчику
GET {{baseUrl}}/sensors/7/
Content-Type: application/json
